import { thaiLunar } from './thai-lunar.js';
const weekdays=['','จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์','เสาร์','อาทิตย์'];
const months=['','มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];
const columns='id,draw_date,weekday,day,month,year_be,lunar_side,first_prize,last3_1,last3_2,last2,source';
const json=(data,status=200)=>Response.json(data,{status,headers:{'cache-control':'no-store'}});
const fail=(message,status=400)=>json({detail:message},status);
const digits=(v,n)=>v==null?null:(String(v).replace(/\D/g,'').padStart(n,'0').slice(-n)||null);
function dateFields(v){let s=String(v||'').trim(),m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m){m=s.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})$/);if(m)s=`${m[3]}-${m[2]}-${m[1]}`;else throw Error('รูปแบบวันที่ไม่ถูกต้อง');}else s=m[0];let [y,mo,d]=s.split('-').map(Number);if(y>2400)y-=543;let dt=new Date(Date.UTC(y,mo-1,d));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==mo-1||dt.getUTCDate()!==d)throw Error('วันที่ไม่ถูกต้อง');return {draw_date:dt.toISOString().slice(0,10),weekday:(dt.getUTCDay()+6)%7+1,day:d,month:mo,year_be:y+543};}
function lunarSide(date){return thaiLunar(date).side;}
async function importDraws(db,items){let inserted=0,updated=0,skipped=0,errors=[];for(let i=0;i<items.length;i++){try{const item=items[i],f=dateFields(item.draw_date),first=digits(item.first_prize,6),last2=digits(item.last2,2),lunar=lunarSide(f.draw_date);if(!first||!last2)throw Error('ไม่มีข้อมูลรางวัล');if(!['ข้างขึ้น','ข้างแรม'].includes(lunar))throw Error('ต้องระบุข้างขึ้น/ข้างแรมที่ถูกต้อง');let found=await db.prepare('SELECT id FROM draws WHERE draw_date=?').bind(f.draw_date).first();await db.prepare(`INSERT INTO draws(draw_date,weekday,day,month,year_be,lunar_side,first_prize,last3_1,last3_2,last2,source) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(draw_date) DO UPDATE SET weekday=excluded.weekday,day=excluded.day,month=excluded.month,year_be=excluded.year_be,lunar_side=excluded.lunar_side,first_prize=excluded.first_prize,last3_1=excluded.last3_1,last3_2=excluded.last3_2,last2=excluded.last2,source=excluded.source,updated_at=CURRENT_TIMESTAMP`).bind(f.draw_date,f.weekday,f.day,f.month,f.year_be,lunar,first,digits(item.last3_1,3),digits(item.last3_2,3),last2,item.source||'GLO').run();found?updated++:inserted++;}catch(e){skipped++;if(errors.length<50)errors.push({index:i,error:e.message});}}return {inserted,updated,skipped,total:inserted+updated,errors};}
const GLO='https://www.glo.or.th';
async function gloFetch(path,body={}){const r=await fetch(GLO+path,{method:'POST',headers:{'content-type':'application/json',origin:GLO,referer:GLO+'/mission/awarding/orderby-time'},body:JSON.stringify(body)});if(!r.ok)throw Error('GLO HTTP '+r.status);return r.json();}
function gloItems(payload){
 if(payload?.status===false)throw Error(payload.statusMessage||'GLO API ไม่สำเร็จ');
 let entries=payload?.response??payload?.data??payload;
 if(entries&&typeof entries==='object'&&!Array.isArray(entries)&&Array.isArray(entries.data))entries=entries.data;
 if(!Array.isArray(entries))entries=[entries];
 const values=(part)=>{const arr=Array.isArray(part)?part:Array.isArray(part?.number)?part.number:part?.number!=null?[part.number]:[];return arr.map(x=>typeof x==='object'?(x?.value??x?.number):x).filter(x=>x!==null&&x!==undefined&&String(x)!=='');};
 const result=[];
 for(const e of entries){if(!e?.date||!e?.data)continue;const d=e.data,first=values(d.first),last2=values(d.last2),last3b=values(d.last3b);if(!first.length||!last2.length)continue;
 const draw_date=dateFields(e.date).draw_date;
 result.push({draw_date,first_prize:first[0],last2:last2[0],last3_1:last3b[0]??null,last3_2:last3b[1]??null,lunar_side:lunarSide(draw_date),source:'GLO'});
 }
 return result;
}
async function rows(db,where='',bind=[],limit=''){const data=(await db.prepare(`SELECT ${columns} FROM draws ${where} ORDER BY draw_date DESC ${limit}`).bind(...bind).all()).results;return data.map(r=>({...r,lunar_side:lunarSide(r.draw_date)}));}
function rank(map,key){return [...map].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([v,count])=>({[key]:v,count}));}
async function handler(req,env){const u=new URL(req.url),p=u.pathname,db=env.DB,method=req.method;if(!db)return fail('D1 binding DB is missing',503);
if(p==='/health'){const r=await db.prepare('SELECT COUNT(*) count FROM draws').first();return json({ok:true,database:'d1',draws:r.count,version:'cloudflare-1.0'});}
if(p==='/api/lunar/check'){const date=u.searchParams.get('date');try{return json({ok:true,date,...thaiLunar(date)});}catch(e){return fail(e.message);}}
if(p==='/api/lunar/repair'&&method==='POST'){if(env.ADMIN_TOKEN&&req.headers.get('authorization')!=='Bearer '+env.ADMIN_TOKEN)return fail('Unauthorized',401);const all=await db.prepare('SELECT draw_date,lunar_side FROM draws').all();let updated=0;for(const row of all.results){const side=lunarSide(row.draw_date);if(side!==row.lunar_side){await db.prepare('UPDATE draws SET lunar_side=?,updated_at=CURRENT_TIMESTAMP WHERE draw_date=?').bind(side,row.draw_date).run();updated++;}}return json({ok:true,total:all.results.length,updated,unchanged:all.results.length-updated});}
if(p==='/api/database'){let r=await db.prepare('SELECT COUNT(*) total_draws, MIN(draw_date) oldest_draw, MAX(draw_date) newest_draw FROM draws').first();return json({ok:true,database:'d1',...r});}
if(p==='/api/options'){let y=(await db.prepare('SELECT DISTINCT year_be FROM draws ORDER BY year_be DESC').all()).results;return json({weekdays:weekdays.slice(1).map((label,i)=>({value:i+1,label})),days:Array.from({length:31},(_,i)=>i+1),months:months.slice(1).map((label,i)=>({value:i+1,label})),years:y.map(r=>({value:r.year_be,label:String(r.year_be)})),lunar_sides:['ข้างขึ้น','ข้างแรม']});}
if(p==='/api/draws'){let n=Number(u.searchParams.get('limit')||100);if(!Number.isInteger(n)||n<1||n>5000)return fail('limit ไม่ถูกต้อง');let data=await rows(db,'',[],`LIMIT ${n}`);return json({ok:true,count:data.length,rows:data});}
if(p==='/api/analyze'){let filters=[],bind=[],lunarFilter=null;for(const k of ['weekday','day','month','year_be','lunar_side']){let v=u.searchParams.get(k);if(v!==null&&v!==''){if(k==='lunar_side'){if(!['ข้างขึ้น','ข้างแรม'].includes(v))return fail('lunar_side ไม่ถูกต้อง');lunarFilter=v;continue;}else{v=Number(v);if(!Number.isInteger(v)||({weekday:v<1||v>7,day:v<1||v>31,month:v<1||v>12})[k])return fail(k+' ไม่ถูกต้อง');}filters.push(k+'=?');bind.push(v);}}let data=await rows(db,filters.length?'WHERE '+filters.join(' AND '):'',bind);if(lunarFilter)data=data.filter(r=>r.lunar_side===lunarFilter);let exact=new Map(),pairs=new Map(),tens=new Map(),units=new Map();for(let r of data){let n=r.last2;for(let [map,k] of [[exact,n],[pairs,[...n].sort().join('')],[tens,n[0]],[units,n[1]]])map.set(k,(map.get(k)||0)+1);}let first3Exact=new Map(),first3Pairs=new Map(),hundreds=new Map(),first3Tens=new Map(),first3Units=new Map();for(const r of data){const n=String(r.first_prize||'').slice(-3).padStart(3,'0');if(!/^\d{3}$/.test(n))continue;for(const [map,k] of [[first3Exact,n],[first3Pairs,[...n].sort().join('')],[hundreds,n[0]],[first3Tens,n[1]],[first3Units,n[2]]])map.set(k,(map.get(k)||0)+1);}return json({ok:true,count:data.length,rows:data,statistics:{exact_last2:rank(exact,'number'),swapped_pair:rank(pairs,'pair'),tens:rank(tens,'digit'),units:rank(units,'digit'),first_prize_last3:{exact:rank(first3Exact,'number'),permutations:rank(first3Pairs,'digits'),hundreds:rank(hundreds,'digit'),tens:rank(first3Tens,'digit'),units:rank(first3Units,'digit')}}});}
if(p==='/api/backtest'){let n=Number(u.searchParams.get('window')||12),swap=u.searchParams.get('use_swap')!=='false';if(!Number.isInteger(n)||n<2||n>200)return fail('window ไม่ถูกต้อง');let data=(await db.prepare('SELECT last2 FROM draws ORDER BY draw_date DESC LIMIT ?').bind(n+1).all()).results,hits=0,tests=Math.max(0,data.length-1);for(let i=0;i<tests;i++){let prev=data[i+1].last2,target=data[i].last2;if(target===prev||(swap&&target===prev.split('').reverse().join('')))hits++;}return json({ok:true,tests,hits,hit_rate:tests?hits/tests:0});}
if(method==='POST'&&['/api/import','/api/import/glo','/api/import/range'].includes(p)){if(env.ADMIN_TOKEN&&req.headers.get('authorization')!=='Bearer '+env.ADMIN_TOKEN)return fail('Unauthorized',401);let payload=await req.json(),draws=payload.draws;if(!Array.isArray(draws))return fail('draws ต้องเป็น array');return json({ok:true,...await importDraws(db,draws)});}
if(p==='/api/glo/debug'){const raw=await gloFetch('/api/lottery/getLatestLottery');const sample=Array.isArray(raw)?raw[0]:raw?.response?.[0]??raw?.response??raw?.data?.[0]??raw?.data??null;return json({ok:true,top_level_type:Array.isArray(raw)?'array':typeof raw,top_level_keys:raw&&typeof raw==='object'?Object.keys(raw):[],status:raw?.status??null,statusMessage:raw?.statusMessage??null,response_type:Array.isArray(raw?.response)?'array':typeof raw?.response,response_count:Array.isArray(raw?.response)?raw.response.length:null,data_type:Array.isArray(raw?.data)?'array':typeof raw?.data,data_count:Array.isArray(raw?.data)?raw.data.length:null,sample:sample&&typeof sample==='object'?JSON.stringify(sample).slice(0,2500):sample});}
if(p==='/api/glo/latest'){let raw=await gloFetch('/api/lottery/getLatestLottery'),data=gloItems(raw);if(!data.length)return fail('GLO ส่งข้อมูลที่อ่านเป็นผลรางวัลไม่ได้ กรุณาตรวจสอบโครงสร้าง API',502);return json({ok:true,source:'GLO',count:data.length,draws:data});}
if(method==='POST'&&['/api/glo/import-latest','/api/glo/import-range'].includes(p)){if(env.ADMIN_TOKEN&&req.headers.get('authorization')!=='Bearer '+env.ADMIN_TOKEN)return fail('Unauthorized',401);let years=[],errors=[];if(p.endsWith('import-range')){let b=await req.json(),a=b.start_year,z=b.end_year;if(!Number.isInteger(a)||!Number.isInteger(z)||a>z||z-a>20)return fail('ช่วงปีไม่ถูกต้อง');for(let y=a;y<=z;y++)years.push(y);}let data=[];if(years.length){for(let y of years){try{data.push(...gloItems(await gloFetch('/api/lottery/getLotteryResultByYear',{year:String(y-543)})));}catch(e){errors.push({year_be:y,error:e.message});}}}else data=gloItems(await gloFetch('/api/lottery/getLatestLottery'));if(!data.length)return fail('ไม่พบผลสลากที่นำเข้าได้จาก GLO: ไม่มีการบันทึกข้อมูล กรุณาตรวจสอบ API ต้นทาง',502);let unique=[...new Map(data.map(x=>[x.draw_date,x])).values()];return json({ok:true,source:'GLO',mode:years.length?'range':'latest',...(years.length?{start_year:years[0],end_year:years.at(-1)}:{}),fetched:unique.length,...await importDraws(db,unique),errors});}
return env.ASSETS.fetch(req);}
export default {async fetch(req,env){try{return await handler(req,env)}catch(e){return fail(e.message||'Internal error',500)}}};
